# Ruff configuration for ruleIQ
target-version = "py38"
line-length = 100

[lint]
select = [
    "F",   # Pyflakes (critical errors only)
]

ignore = [
    # Disable all style and formatting rules
    "E",    # All pycodestyle errors
    "W",    # All pycodestyle warnings
    "N",    # pep8-naming
    "UP",   # pyupgrade
    "B",    # flake8-bugbear
    "C4",   # flake8-comprehensions
    "SIM",  # flake8-simplify
    "RUF",  # Ruff-specific rules
    "I",    # isort
    "D",    # pydocstyle
]

# Directories to exclude
exclude = [
    ".git",
    "__pycache__",
    ".venv",
    "venv",
    ".env",
    "env",
    "build",
    "dist",
    "htmlcov",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
    "migrations",
]

[lint.per-file-ignores]
"tests/*" = ["SIM117", "B011"]
"*/__init__.py" = ["F401"]  # Allow unused imports in __init__.py

[lint.isort]
known-first-party = ["api", "database", "services", "config", "core"]
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]

[format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"